version: "3"
services:
  nodejs:
    container_name: nodejs
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: /root/app/node_modules/.bin/nodemon /root/app/server.js
    ports:
    - "3000:3000"
    - "8080:8080"
    - "9000:9000"
    depends_on:
    - mongo
    environment:
      WAIT_HOSTS: mongo:27017 
  mongo:
    container_name: mongo
    image: mongo
    ports:
    - "27017:27017"
  